# Settings for client copyright
client:
  name: CZEPA
  year: 2016
  url: http://www.czepa.cz
  image: admin_footer_logo_client.png

# Settings for developer copyright
developer:
  name: Anuba Design
  year: 2012
  url: http://www.anuba.cz
  image: admin_footer_logo_clockstar.png