items:
  -
    label: headers.admin.candidates.index
    url: main_app.admin_candidates_path
    icon: user
    active_if: "controller_name == 'candidates'"
  -
    label: headers.admin.elections.index
    url: main_app.admin_elections_path
    icon: globe
    active_if: "controller_name == 'elections'"
